# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Deploy to Github Pages
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm i
        CI='' npm run build --if-present
      env:
        REACT_APP_WEATHER_APP_ID: ${{APP_ID}}

    - name: Deploy
      run: |
        git config --global user.email ${{secrets.GITHUBEMAIL}}
        git config --global user.name ${{secrets.GITHUBUSERNAME}}
        git remote set-url origin https://${{secrets.TOKEN}}@github.com/${{secrets.GITHUBUSERNAME}}/typescript-react-weather-app.git
        npm run deploy