name: Deploy workflow to S3

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: CI='' npm run build
        env:
          REACT_APP_WEATHER_APP_ID: ${{APP_ID}}

      - name: deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'typescript-react-weather-app'
          AWS_ACCESS_KEY_ID: ${{AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{AWS_ACCESS_KEY_ID}}
          AWS_REGION: ${{AWS_REGION}}   # optional: defaults to us-east-1
          SOURCE_DIR: 'build'      # optional: defaults to entire repository
